### ISSUE TITLE
Do you have a 3D model of Clervie?

### ISSUE THREAD

**Issue by kdjjdr** [ladyfoxpoint/anime-game-assets#1]
![Uploading GL5WW-oXQAATUdD.png…]()

**Comment by ladyfoxpoint** [comment]
Unfortunately I haven't been able to extract models from 4.6 yet. The ones I have uploaded are from a trusted source that has been able to but can't share everything.
There might be a little bit of time before I can start getting those. 
Sorry about that ^^,

**Comment by kdjjdr** [comment]
Okay, thanks for the answer.

**Comment by ladyfoxpoint** [comment]
This model has been uploaded in:
https://github.com/ladyfoxpoint/anime-game-assets/commit/08bb8a5cc38341e50ea2a9734da816f425543dc8

**Comment by kdjjdr** [comment]
Thank you.
